/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProviderFinance;

import Business.CDCSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import UserInterface.ProviderAdmin.UpdatePersonalInfoJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */
public class ProviderFinanceWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ProviderFinanceWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private CDCSystem system;
    private DB4OUtil db4oUtil;
    
    public ProviderFinanceWorkArea(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, CDCSystem system, DB4OUtil db4oUtil) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.account= account;
        this.enterprise= enterprise;
        this.system= system;
        this.db4oUtil= db4oUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        updatePersonalInfoButton = new javax.swing.JButton();
        manageTreasuryButton = new javax.swing.JButton();
        manageReceivingPaymentButton = new javax.swing.JButton();
        managePaymentButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 245, -1));

        updatePersonalInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePersonalInfoButton.setText("Update Personal Info");
        updatePersonalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePersonalInfoButtonActionPerformed(evt);
            }
        });
        add(updatePersonalInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 245, -1));

        manageTreasuryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageTreasuryButton.setText("Manage Treasury");
        manageTreasuryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTreasuryButtonActionPerformed(evt);
            }
        });
        add(manageTreasuryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 245, -1));

        manageReceivingPaymentButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageReceivingPaymentButton.setText("Manage Receiving Payments");
        manageReceivingPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReceivingPaymentButtonActionPerformed(evt);
            }
        });
        add(manageReceivingPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 245, -1));

        managePaymentButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        managePaymentButton.setText("Manage Payment Requests");
        managePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePaymentButtonActionPerformed(evt);
            }
        });
        add(managePaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 245, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Provider Finance Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 265, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        db4oUtil.storeSystem(system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void updatePersonalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePersonalInfoButtonActionPerformed
        // TODO add your handling code here:
        UpdatePersonalInfoJPanel updatePersonalInfoJPanel = new UpdatePersonalInfoJPanel(userProcessContainer, system, account);
        userProcessContainer.add("updatePersonalInfoJPanel", updatePersonalInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updatePersonalInfoButtonActionPerformed

    private void manageTreasuryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTreasuryButtonActionPerformed
        // TODO add your handling code here:
        ManageTreasuryProviderJPanel manageTreasuryProvider = new ManageTreasuryProviderJPanel(userProcessContainer, system, enterprise, account);
        userProcessContainer.add("ManageTreasuryProviderJPanel", manageTreasuryProvider);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageTreasuryButtonActionPerformed

    private void manageReceivingPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReceivingPaymentButtonActionPerformed
        // TODO add your handling code here:
        ManageReceivingProviderJPanel manageReceivingProvider = new ManageReceivingProviderJPanel(userProcessContainer, system, enterprise, account);
        userProcessContainer.add("ManageReceivingProviderJPanel", manageReceivingProvider);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReceivingPaymentButtonActionPerformed

    private void managePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePaymentButtonActionPerformed
        // TODO add your handling code here:
        ManagePaymentProviderJPanel managePaymentsProvider = new ManagePaymentProviderJPanel(userProcessContainer, system, enterprise, account);
        userProcessContainer.add("ManagePaymentProviderJPanel", managePaymentsProvider);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePaymentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton managePaymentButton;
    private javax.swing.JButton manageReceivingPaymentButton;
    private javax.swing.JButton manageTreasuryButton;
    private javax.swing.JButton updatePersonalInfoButton;
    // End of variables declaration//GEN-END:variables
}
