/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.CDCSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.DistributorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    private JPanel userProcessContainer;
    private CDCSystem system;
    private DB4OUtil db4oUtil;
    private Enterprise inEnterprise;
    private Organization inOrganization;
    private UserAccount userAccount = null;

    public LoginJPanel(JPanel userProcessConatiner, CDCSystem system, DB4OUtil db4oUtil) {
        initComponents();
        this.userProcessContainer = userProcessConatiner;
        this.system = system;
        this.db4oUtil = db4oUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextFieldActionPerformed(evt);
            }
        });
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 224, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 149, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 147, -1));

        loginButton.setBackground(new java.awt.Color(255, 204, 204));
        loginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 126, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("National Vaccine Distribution System");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 449, -1));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 224, 27));

        registerButton.setBackground(new java.awt.Color(255, 204, 204));
        registerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 152, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextFieldActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_usernameJTextFieldActionPerformed
    public UserAccount checkSubnetworks(Network network1, String username, String password) {

        for (Network network : network1.getNetworkList()) {
            //Step 2-a: Check against each enterprise
           
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                userAccount = enterprise.getUserAccountDirectory().authenticateUser(username, password);
                if (userAccount == null) {
                    //Step3: Check against each organization inside that enterprise
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        userAccount = organization.getUserAccountDirectory().authenticateUser(username, password);

                        if (userAccount != null) {
                            inEnterprise = enterprise;
                            inOrganization = organization;
                            break;
                        }
                    }
                } else {
                    inEnterprise = enterprise;
                    break;
                }
                if (inOrganization != null) {
                    break;
                }
            }
            if (inEnterprise != null) {
                break;
            }
        }
        if (userAccount == null) {
            return null;
        }
        return userAccount;
    }
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        inEnterprise = null;
        inOrganization = null;
        // Get user name
        String userName = usernameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system user account directory if you have the user
        userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        if (userAccount == null) {
            userAccount = system.getNationalDistributor().getUserAccountDirectory().authenticateUser(userName, password);

            if (userAccount != null) {
                DistributorEnterprise de = new DistributorEnterprise();
                inEnterprise = de;
            }
        }
        Network network1 = system.getNetwork();
        if (userAccount == null) {
            //Step2: Go inside each network to check each enterprise
            for (Network network : network1.getNetworkList()) {
                //Step 2-a: Check against each enterprise
                userAccount = checkSubnetworks(network, userName, password);
                if (userAccount == null) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {
                            //Step3: Check against each organization inside that enterprise
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if (userAccount != null) {
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    break;
                                }
                            }
                        } else {
                            inEnterprise = enterprise;
                            break;
                        }
                        if (inOrganization != null) {
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }

                } else {
                    break;
                }
            }
        }

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
        } else {
            usernameJTextField.setText(null);
            passwordField.setText(null);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("workArea", userAccount.getRoles().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, system, db4oUtil));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        RegisterJPanel registerJPanel = new RegisterJPanel(userProcessContainer, system, db4oUtil);
        userProcessContainer.add("ManageEnterpriseAdminJPanel", registerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
