/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PHDAdmin;

import Business.CDCSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReportVaccineRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danisha
 */
public class ReportCDCJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportCDCJPanel
     */
    private JPanel userProcessContainer;
    private CDCSystem system;
    private UserAccount account;
    private Enterprise enterprise;
    public ReportCDCJPanel(JPanel userProcessContainer, CDCSystem system, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system= system;
        this.account= account;
        this.enterprise= enterprise;
        populate();
    }

    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel) reportVaccineJTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestType().equals("Report")) {
                ReportVaccineRequest report = (ReportVaccineRequest) request;
                Object row[] = new Object[5];
                row[0] = report.getVaccine().getVaccineId();
                row[1] = report;
                row[2] = request.getRequestDate();
                row[3] = request.getStatus();
                row[4] = request.getResolveDate();
                dtm.addRow(row);
            }
        }
    

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vaccineNameJTextField = new javax.swing.JTextField();
        effectsJTextField = new javax.swing.JTextField();
        messageJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportVaccineJTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        backButton1 = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Bad Effects");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Message");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 78, 25));

        vaccineNameJTextField.setEditable(false);
        vaccineNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vaccineNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineNameJTextFieldActionPerformed(evt);
            }
        });
        add(vaccineNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 203, -1));

        effectsJTextField.setEditable(false);
        effectsJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        effectsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effectsJTextFieldActionPerformed(evt);
            }
        });
        add(effectsJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 337, 78));

        messageJTextField.setEditable(false);
        messageJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        messageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageJTextFieldActionPerformed(evt);
            }
        });
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 337, 78));

        reportVaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Id", "Name", "Report Date", "Status", "Response Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportVaccineJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 946, 158));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Vaccine Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, 25));

        backButton1.setBackground(new java.awt.Color(255, 204, 204));
        backButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 98, -1));

        forwardButton.setBackground(new java.awt.Color(255, 204, 204));
        forwardButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        forwardButton.setText("Forward to CDC");
        forwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardButtonActionPerformed(evt);
            }
        });
        add(forwardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, -1, -1));

        refreshButton.setBackground(new java.awt.Color(255, 204, 204));
        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, -1));

        viewButton.setBackground(new java.awt.Color(255, 204, 204));
        viewButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Report Vaccine Requests");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void vaccineNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineNameJTextFieldActionPerformed

    private void effectsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effectsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_effectsJTextFieldActionPerformed

    private void messageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageJTextFieldActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void forwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = reportVaccineJTable.getSelectedRow();
        if (selectedRow >= 0) {
            ReportVaccineRequest report= new ReportVaccineRequest();
            report = (ReportVaccineRequest) reportVaccineJTable.getValueAt(selectedRow, 1);
            report.setStatus("Approved from PHD & Pending from CDC");
            Date date= new Date();
            report.setResolveDate(date);
            WorkRequest request= report;
            system.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request forwarded to CDC");
        }else if (selectedRow > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        populate();
    }//GEN-LAST:event_forwardButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        populate();
        vaccineNameJTextField.setText(null);
        messageJTextField.setText(null);
        effectsJTextField.setText(null);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = reportVaccineJTable.getSelectedRow();
        if (selectedRow >= 0) {
            ReportVaccineRequest report = (ReportVaccineRequest) reportVaccineJTable.getValueAt(selectedRow, 1);
            vaccineNameJTextField.setText(report.getVaccine().getVaccineName());
            messageJTextField.setText(report.getMessage());
            effectsJTextField.setText(report.getEffects());
        }else if (selectedRow > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        populate();
    }//GEN-LAST:event_viewButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField effectsJTextField;
    private javax.swing.JButton forwardButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable reportVaccineJTable;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
