/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CDCFinance;

import Business.CDCSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danisha
 */
public class CDCFinanceWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CDCFinanceWorkArea
     */
    private JPanel userProcessContainer;
    private CDCSystem system;
    private UserAccount account;
    private DB4OUtil db4outil;

    public CDCFinanceWorkArea(JPanel userProcessContainer, CDCSystem system, UserAccount account, DB4OUtil db4outil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.db4outil = db4outil;
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) paymentTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : system.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestType().equals("Finance")) {
                FinanceRequest finance = (FinanceRequest) request;
                if (finance.getFinanceType().equals("p to cdc")) {
                    Object row[] = new Object[5];
                    row[0] = finance.getRequestID();
                    row[1] = finance.getStatus();
                    row[2] = finance.getRequestDate();
                    row[3] = finance.getSenderEnterprise().getEnterpriseName();
                    row[4] = finance.getTotalAmount();
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * t
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewOrderButton2 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        billingDateTextField = new javax.swing.JTextField();
        payAmountButton = new javax.swing.JButton();
        ageTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        insuranceNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        insurancePercentageTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        insuranceTypeTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewOrderButton2.setBackground(new java.awt.Color(255, 204, 204));
        viewOrderButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewOrderButton2.setText("View Request");
        viewOrderButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderButton2ActionPerformed(evt);
            }
        });
        add(viewOrderButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 140, -1));

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 111, 34));

        paymentTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Status", "Request Date", "Receiver Enterprise", "Amount Due"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(paymentTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 820, 170));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CDC Finance Work Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, 20));

        totalAmountTextField.setEditable(false);
        totalAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountTextFieldActionPerformed(evt);
            }
        });
        add(totalAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 141, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Billing Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        billingDateTextField.setEditable(false);
        billingDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingDateTextFieldActionPerformed(evt);
            }
        });
        add(billingDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 141, 31));

        payAmountButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        payAmountButton.setText("Pay Amount");
        payAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payAmountButtonActionPerformed(evt);
            }
        });
        add(payAmountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 133, -1));

        ageTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 240, 196, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, -1, -1));

        lastNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 190, 196, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Contact Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, -1));

        contactNumberTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });
        add(contactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 280, 196, -1));

        insuranceNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insuranceNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceNameTextFieldActionPerformed(evt);
            }
        });
        add(insuranceNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 330, 196, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Last Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Patient Details");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Insurance Percentage");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, -1));

        firstNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 140, 196, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Insurance Type");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Insurance Name");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, -1, -1));

        insurancePercentageTextField.setEditable(false);
        insurancePercentageTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insurancePercentageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insurancePercentageTextFieldActionPerformed(evt);
            }
        });
        add(insurancePercentageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 430, 196, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("First Name");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, -1, -1));

        insuranceTypeTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insuranceTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceTypeTextFieldActionPerformed(evt);
            }
        });
        add(insuranceTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 380, 196, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total Amount");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrderButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentTable.getSelectedRow();
        FinanceRequest selectedOrder = null;
        if (selectedRow >= 0) {
            int requestID = (Integer) paymentTable.getValueAt(selectedRow, 0);
            for (WorkRequest request : system.getWorkQueue().getWorkRequestList()) {
                if (request.getRequestID() == requestID) {
                    selectedOrder = (FinanceRequest) request;
                }
            }
            totalAmountTextField.setText(String.valueOf(selectedOrder.getTotalAmount()));
            billingDateTextField.setText(String.valueOf(selectedOrder.getBillingDate()));
            firstNameTextField.setText(selectedOrder.getPatient().getPatientName());
            lastNameTextField.setText(selectedOrder.getPatient().getLastName());
            ageTextField.setText(String.valueOf(selectedOrder.getPatient().getAge()));
            contactNumberTextField.setText(selectedOrder.getPatient().getContactNo());
            insuranceNameTextField.setText(selectedOrder.getPatient().getInsuranceName());
            insurancePercentageTextField.setText(String.valueOf(selectedOrder.getPatient().getInsurancePercentage()));
            insuranceTypeTextField.setText(selectedOrder.getPatient().getInsuredType());

        } else if (selectedRow > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_viewOrderButton2ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        db4outil.storeSystem(system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void totalAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountTextFieldActionPerformed

    private void billingDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingDateTextFieldActionPerformed

    private void payAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payAmountButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentTable.getSelectedRow();
        FinanceRequest selectedOrder = null;
        if (selectedRow >= 0) {
            int requestID = (Integer) paymentTable.getValueAt(selectedRow, 0);
            for (WorkRequest request : system.getWorkQueue().getWorkRequestList()) {
                if (request.getRequestID() == requestID) {
                    selectedOrder = (FinanceRequest) request;
                    break;
                }
            }
            Date date = new Date();
            selectedOrder.setPaidDate(date);
            selectedOrder.setStatus("Paid by CDC");
            JOptionPane.showMessageDialog(null, "Payment Paid Successfully");
        } else if (selectedRow > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        populate();
        totalAmountTextField.setText(null);
        billingDateTextField.setText(null);

    }//GEN-LAST:event_payAmountButtonActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void insuranceNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceNameTextFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void insurancePercentageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insurancePercentageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insurancePercentageTextFieldActionPerformed

    private void insuranceTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceTypeTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField billingDateTextField;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField insuranceNameTextField;
    private javax.swing.JTextField insurancePercentageTextField;
    private javax.swing.JTextField insuranceTypeTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton payAmountButton;
    private javax.swing.JTable paymentTable;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JButton viewOrderButton2;
    // End of variables declaration//GEN-END:variables
}
