/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManufacturerAdmin;

import Business.CDCSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.WorkQueue.OrderRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */
public class ManufactureVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufactureVaccineJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private CDCSystem system;
    private WorkRequest request;
    private UserAccount account;
    private OrderRequest orderRequest;
    private ManufacturerEnterprise manufacturerEnterprise;

    public ManufactureVaccineJPanel(JPanel userProcessContainer, Enterprise enterprise, CDCSystem system, WorkRequest request, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.request = request;
        this.account = account;
        orderRequest = (OrderRequest) request;
        manufacturerEnterprise = (ManufacturerEnterprise) enterprise;
        populateCombo();
    }

    public void populateCombo() {
        vaccineNameJComboBox.removeAllItems();
        for (OrderItem orderItem : orderRequest.getOrder().getOrderItemList()) {
            vaccineNameJComboBox.addItem(orderItem.getVaccine());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quanitytJTextField = new javax.swing.JTextField();
        vaccineNameJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unitPriceJTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        backButton.setBackground(new java.awt.Color(255, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Vaccine");

        quanitytJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quanitytJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanitytJTextFieldActionPerformed(evt);
            }
        });

        vaccineNameJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Unit Price");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");

        unitPriceJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unitPriceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitPriceJTextFieldActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(255, 204, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Manufacture Vaccines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quanitytJTextField)
                    .addComponent(vaccineNameJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unitPriceJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vaccineNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quanitytJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(unitPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void quanitytJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanitytJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanitytJTextFieldActionPerformed

    private void unitPriceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitPriceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitPriceJTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        Vaccine vaccine = (Vaccine) vaccineNameJComboBox.getSelectedItem();
        float totalAmount = 0;
       /* try {
            float price = Float.parseFloat(unitPriceJTextField.getText());
            for (OrderItem orderItem : orderRequest.getOrder().getOrderItemList()) {
                if (orderItem.getVaccine().equals(vaccine)) {
                    orderItem.setQuantity();
                    v.setVaccineId(orderItem.getVaccine().getVaccineId());
                    v.setVaccineName(orderItem.getVaccine().getVaccineName());
                    oi.setQuantity(orderItem.getQuantity());
                    v.setBasePrice(price);
                    Calendar cal = Calendar.getInstance();
                    Date DOM = cal.getTime();
                    cal.add(Calendar.YEAR, 1);
                    Date DOE = cal.getTime();
                    v.setDateOfManufacture(new SimpleDateFormat("MM-dd-yyyy").format(DOM));
                    v.setDateOfExpiry(new SimpleDateFormat("MM-dd-yyyy").format(DOE));
                    v.setDiseaseName(orderItem.getVaccine().getDiseaseName());
                    v.setManufacturer(manufacturerEnterprise);

                    orderItem.getVaccine().setBasePrice(price);
                    orderItem.setSalesPrice(price);
                    orderItem.getVaccine().setManufacturer(manufacturerEnterprise);
                    orderItem.getVaccine().setDateOfManufacture(new SimpleDateFormat("MM-dd-yyyy").format(DOM));
                    orderItem.getVaccine().setDateOfExpiry(new SimpleDateFormat("MM-dd-yyyy").format(DOE));
                    orderWorkRequest.setResolveDate(DOM);

                    float tempTotal = orderItem.getQuantity() * price;
                    totalAmount = totalAmount + tempTotal;
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please provide a valid price");
            return;
        }
        orderWorkRequest.setStatus("Manufactured");

        //creating a finance work request
        ManufacturerEnterprise me = (ManufacturerEnterprise) enterprise;
        float treasuryUpdate = me.getTreasury() - totalAmount;
        me.setTreasury(treasuryUpdate);
        FinanceWorkRequest financeWorkRequest = new FinanceWorkRequest();
        WorkRequest workRequest = financeWorkRequest;
        financeWorkRequest.setOrder(orderWorkRequest.getOrder());
        financeWorkRequest.setSender(userAccount);
        financeWorkRequest.setTotalAmount(totalAmount);
        Date date = new Date();
        financeWorkRequest.setBillingDate(new SimpleDateFormat("MM-dd-yyyy").format(date));
        financeWorkRequest.setPaymentType("Outgoing");
        financeWorkRequest.setPaymentMode("N/A");
        financeWorkRequest.setPaidDate("N/A");
        userAccount.getWorkQueue().getWorkRequestList().add(workRequest);

        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o.getName().equals(Organization.Type.Finance.getValue())) {
                o.getWorkQueue().getWorkRequestList().add(workRequest);
            }
        }
        /*Network country = system.getNetwork1();
        
         for(Network states: country.getNetworkDirectory()){
         if(states.getName().equals(enterprise.getNetwork())){
         for(Enterprise e: states.getEnterpriseDirectory().getEnterpriseList()){
         if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Distributor)){
         for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
         if(o.getName().equals(Organization.Type.Finance.getValue())){
         o.getWorkQueue().getWorkRequestList().add(workRequest);
         }
         }
         }
         }
         }
         }*/
        /*for(Network states: country.getNetworkDirectory()){
         if(states.getName().equals(enterprise.getNetwork())){
         for(Network cities : states.getNetworkDirectory()){
         for(Enterprise e: cities.getEnterpriseDirectory().getEnterpriseList()){
         if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Provider)){
         for(UserAccount ua: e.getUserAccountDirectory().getUserAccountList()){
         if(ua == orderWorkRequest.getSender()){
         for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
         if(o.getName().equals(Organization.Type.Finance.getValue())){
         o.getWorkQueue().getWorkRequestList().add(workRequest);
         }
         }
         }
         }
         }
         }
         }
         }
            
         }*/
        JOptionPane.showMessageDialog(null, "Manufacture of vaccination is successful!");
    }//GEN-LAST:event_submitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField quanitytJTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField unitPriceJTextField;
    private javax.swing.JComboBox vaccineNameJComboBox;
    // End of variables declaration//GEN-END:variables
}
