/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProviderAdmin;

import Business.CDCSystem;
import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */
public class UpdatePersonalInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonalInfoJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private CDCSystem system;

    public UpdatePersonalInfoJPanel(JPanel userProcessContainer, CDCSystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        String firstName = account.getEmployee().getName();
        String lastName = account.getEmployee().getLastName();
        String address1 = account.getEmployee().getAddress();
        String address2=account.getEmployee().getAddress2();
        firstNameJTextField.setText(firstName);
        lastNameJTextField.setText(lastName);
        usernameJTextField.setText(account.getUsername());
        passwordJTextField.setText(account.getPassword());
        address1JTextField.setText(address1);
        address2JTextField.setText(address2);
        contactNoJTextField.setText(account.getEmployee().getConatctNumber());
        emailIdJTextField.setText(account.getEmployee().getEmailID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        address2JTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JTextField();
        contactNoJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailIdJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        usernameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        address1JTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Contact No.");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Address2");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        address2JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address2JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address2JTextFieldActionPerformed(evt);
            }
        });
        add(address2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 203, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Email ID");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        passwordJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJTextFieldActionPerformed(evt);
            }
        });
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 203, -1));

        contactNoJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoJTextFieldActionPerformed(evt);
            }
        });
        add(contactNoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 186, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        emailIdJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailIdJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdJTextFieldActionPerformed(evt);
            }
        });
        add(emailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 203, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        lastNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameJTextFieldActionPerformed(evt);
            }
        });
        add(lastNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 203, -1));

        usernameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextFieldActionPerformed(evt);
            }
        });
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 186, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("First Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        firstNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameJTextFieldActionPerformed(evt);
            }
        });
        add(firstNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 186, -1));

        submitButton.setBackground(new java.awt.Color(255, 204, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Address1");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        address1JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address1JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1JTextFieldActionPerformed(evt);
            }
        });
        add(address1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 186, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Update Personal Info");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void address2JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address2JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address2JTextFieldActionPerformed

    private void passwordJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJTextFieldActionPerformed

    private void contactNoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNoJTextFieldActionPerformed

    private void emailIdJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdJTextFieldActionPerformed

    private void lastNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJTextFieldActionPerformed

    private void usernameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJTextFieldActionPerformed

    private void firstNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        String address = address1JTextField.getText() + " " + address2JTextField.getText();
        String contactNo = contactNoJTextField.getText();
        String emailID = emailIdJTextField.getText();
        
        
            Employee employee = account.getEmployee();
            employee.setAddress(address);
            employee.setConatctNumber(contactNo);
            employee.setEmailID(emailID);
            JOptionPane.showMessageDialog(null, "Details Submitted");
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void address1JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1JTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1JTextField;
    private javax.swing.JTextField address2JTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contactNoJTextField;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
