/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProviderAdmin;

import Business.CDCSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProviderEnterprise;
import Business.Provider.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */

public class ViewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientJPanel
     */
    private JPanel userProcessContainer;
    private CDCSystem system;
    private UserAccount account;
    private Enterprise enterprise;
    private ProviderEnterprise pe;
    private Patient patient;
    
    public ViewPatientJPanel(JPanel userProcessContainer, CDCSystem system, Enterprise enterprise, Patient patient) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise= enterprise;
        this.system= system;
        this.patient= patient;
        firstNameTextField.setText(patient.getPatientName());
        lastNameTextField.setText(patient.getLastName());
        ageTextField.setText(String.valueOf(patient.getAge()));
        contactNumberTextField.setText(patient.getContactNo());
        insuranceNameTextField.setText(patient.getInsuranceName());
        insuranceTypeComboBox.setSelectedItem(patient.getInsuredType());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insuranceNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        insuranceTypeComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ageTextField.setEditable(false);
        ageTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 196, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        lastNameTextField.setEditable(false);
        lastNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 196, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Contact Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        contactNumberTextField.setEditable(false);
        contactNumberTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });
        add(contactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 196, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Patient Info");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        insuranceNameTextField.setEditable(false);
        insuranceNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insuranceNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceNameTextFieldActionPerformed(evt);
            }
        });
        add(insuranceNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 196, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        insuranceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fully Insured", "Partially Insured", "Un-Insured" }));
        add(insuranceTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 196, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("First Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        submitButton.setBackground(new java.awt.Color(255, 204, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 98, -1));

        firstNameTextField.setEditable(false);
        firstNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 196, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Insurance Type");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Insurance Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 98, -1));

        updateButton.setBackground(new java.awt.Color(255, 204, 204));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 98, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void insuranceNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceNameTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try {
            String name = firstNameTextField.getText();
            String lastName = lastNameTextField.getText();
            String contactNo = contactNumberTextField.getText();
            String insuranceName = insuranceNameTextField.getText();
            String age1 = ageTextField.getText();
            int age = Integer.parseInt(ageTextField.getText());
            if (!(name.isEmpty()) && !(lastName.isEmpty()) && !(contactNo.isEmpty()) && !(insuranceName.isEmpty()) && !(age1.isEmpty())) {
                
                patient.setAge(age);
                patient.setPatientName(name);
                patient.setLastName(lastName);
                patient.setContactNo(contactNo);
                String insuranceType = String.valueOf(insuranceTypeComboBox.getSelectedItem());
                patient.setInsuredType(insuranceType);
                JOptionPane.showMessageDialog(null, "Details Submitted");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter apprpriate details");
        }
        firstNameTextField.setText(null);
        lastNameTextField.setText(null);
        contactNumberTextField.setText(null);
        insuranceNameTextField.setText(null);
        ageTextField.setText(null);
        insuranceTypeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        submitButton.setEnabled(true);
        firstNameTextField.setEditable(true);
        lastNameTextField.setEditable(true);
        contactNumberTextField.setEditable(true);
        ageTextField.setEditable(true);
        insuranceNameTextField.setEditable(true);
        insuranceTypeComboBox.setSelectedIndex(0);
        
    }//GEN-LAST:event_updateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField insuranceNameTextField;
    private javax.swing.JComboBox insuranceTypeComboBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
