/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CDCSystemAdmin;

import Business.CDCSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Roles.DistributorAdminRole;
import Business.Roles.Roles;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */
public class AddAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addAdminJPanel
     */
    private JPanel userProcessContainer;
    private CDCSystem system;

    public AddAdminJPanel(JPanel userProcessContainer, CDCSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateCombo() {
        stateComboBox.removeAllItems();

        for (Network network : system.getNetwork().getNetworkList()) {
            stateComboBox.addItem(network);
        }

    }

    public void populateComboEnterprise(Network network) {
        enterpriseComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Manufacturer)) {
                enterpriseComboBox.addItem(enterprise);
            }
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        stateComboBox = new javax.swing.JComboBox();
        enterpriseComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJTextFieldActionPerformed(evt);
            }
        });
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 166, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Add Admin");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        nameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 166, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        submitButton.setBackground(new java.awt.Color(255, 204, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setText("Submit Changes");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Enterprise");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        usernameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextFieldActionPerformed(evt);
            }
        });
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 166, -1));

        backButton.setBackground(new java.awt.Color(255, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, -1));

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });
        add(stateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 160, 20));

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Network");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void passwordJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJTextFieldActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        Network network = (Network) stateComboBox.getSelectedItem();
        Enterprise enterprise = (Enterprise) enterpriseComboBox.getSelectedItem();
        String enterpriseType= enterprise.getEnterpriseType().getValue();
        String username = usernameJTextField.getText();
        String password = passwordJTextField.getText();
        String name = nameJTextField.getText();
        Roles roles = null;
        if (enterpriseType.equals(EnterpriseType.Distributor.getValue())) {
            roles = new DistributorAdminRole();
        }
        for (Enterprise enterprise1 : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise1.getEnterpriseType().getValue().equals(enterpriseType)) {
                enterprise = enterprise1;
                break;
            }
        }
        if (!(username.isEmpty()) && !(password.isEmpty()) && !(name.isEmpty()) && !(system.checkUsernameUnique(system, username))) {
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization.getName().equals(Organization.Type.Admin.getValue())) {
                    Employee employee = new Employee();
                    employee.setName(name);
                    enterprise.getEmployeeDirectory().createEmployee(name);
                    enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, roles);
                    organization.getEmployeeDirectory().getEmployeeList().add(employee);
                    organization.getUserAccountDirectory().createUserAccount(username, password, employee, roles);
                }
            }
            JOptionPane.showMessageDialog(null, "Details Submitted");

        } else {
            JOptionPane.showMessageDialog(null, "Please enter all the fields");
        }


        usernameJTextField.setText(null);
        passwordJTextField.setText(null);
        nameJTextField.setText(null);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void usernameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backButtonActionPerformed

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) stateComboBox.getSelectedItem();
        if (network != null) {
            populateComboEnterprise(network);
        }
    }//GEN-LAST:event_stateComboBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
