/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CDCSystemAdmin;

import Business.CDCSystem;
import Business.Enterprise.DistributorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danisha
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private CDCSystem system;
    private Network network;

    public ManageEnterpriseJPanel(JPanel userProcessContainer, CDCSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateCombo();
        populateComboEnterprise();
    }

    public void populateCombo() {
        stateComboBox.removeAllItems();

        for (Network network : system.getNetwork().getNetworkList()) {
            stateComboBox.addItem(network);
        }

    }

    public void populateComboEnterprise() {
        enterpriseComboBox.removeAllItems();
        enterpriseComboBox.addItem(Enterprise.EnterpriseType.Manufacturer);



    }

    public void populateTable(Network network) {
        DefaultTableModel dtm = (DefaultTableModel) networkTable.getModel();
        dtm.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            Object row[] = new Object[6];
            row[0] = enterprise;
            row[1] = enterprise.getEnterpriseName();
            row[2] = enterprise.getLocation();
            row[3] = enterprise.getContactName();
            row[4] = enterprise.getContactNumber();
            row[5] = enterprise.getEmailId();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeEnterpriseButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkTable = new javax.swing.JTable();
        submitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        contactNameJTextField = new javax.swing.JTextField();
        emailIdJTextField = new javax.swing.JTextField();
        contactNumberJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        enterpriseNameJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeEnterpriseButton.setBackground(new java.awt.Color(255, 204, 204));
        removeEnterpriseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeEnterpriseButton.setText("Remove Enterprise");
        removeEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnterpriseButtonActionPerformed(evt);
            }
        });
        add(removeEnterpriseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 176, -1));

        backButton.setBackground(new java.awt.Color(255, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 98, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Network:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        stateComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });
        add(stateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 189, 28));

        networkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Type", "Enterprise Name", "Location", "Contact name", "Contact Number", "Email ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 1006, 140));

        submitButton.setBackground(new java.awt.Color(255, 204, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setText("Add Enterprise");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("City");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email ID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Contact Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));

        cityJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJTextFieldActionPerformed(evt);
            }
        });
        add(cityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 166, -1));

        contactNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNameJTextFieldActionPerformed(evt);
            }
        });
        add(contactNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 166, -1));

        emailIdJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailIdJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdJTextFieldActionPerformed(evt);
            }
        });
        add(emailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 166, -1));

        contactNumberJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberJTextFieldActionPerformed(evt);
            }
        });
        add(contactNumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 166, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Enterprise Type");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        enterpriseComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(enterpriseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 166, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Manage Enterprise");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        enterpriseNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNameJTextFieldActionPerformed(evt);
            }
        });
        add(enterpriseNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 166, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Enterprise Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void removeEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnterpriseButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = networkTable.getSelectedRow();
        if (selectedRow >= 0) {
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete", "warning", JOptionPane.YES_NO_OPTION);
            Network network = (Network) stateComboBox.getSelectedItem();
            if (option == JOptionPane.YES_OPTION) {
                Enterprise enterprise = (Enterprise) networkTable.getValueAt(selectedRow, 0);
                network.getEnterpriseDirectory().getEnterpriseList().remove(enterprise);
            }
            populateTable(network);
        } else if (selectedRow > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }

    }//GEN-LAST:event_removeEnterpriseButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        // TODO add your handling code here:
        network = (Network) stateComboBox.getSelectedItem();
        populateTable(network);
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try {

            EnterpriseType enterpriseType = (EnterpriseType) enterpriseComboBox.getSelectedItem();
            String type = enterpriseType.getValue();
            String address = cityJTextField.getText();
            String location = network.getName();
            String contactName = contactNameJTextField.getText();
            String enterpriseName = enterpriseNameJTextField.getText();
            String contactNumber = (contactNumberJTextField.getText());
            String emailId = emailIdJTextField.getText();
            if (!(location.isEmpty()) && !(contactName.isEmpty()) && !(emailId.isEmpty()) && !(enterpriseName.isEmpty())) {

                if (type.equals(Enterprise.EnterpriseType.Distributor.getValue())) {
                    DistributorEnterprise distributor = new DistributorEnterprise();
                    Enterprise enterprise = distributor;
                    distributor.setLocation(location);
                    distributor.setAddress(address);
                    distributor.setContactName(contactName);
                    distributor.setContactNumber(contactNumber);
                    distributor.setEmailId(emailId);
                    distributor.setEnterpriseName(enterpriseName);
                    network.getEnterpriseDirectory().getEnterpriseList().add(distributor);
                    enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Inventory);
                    enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Order);

                }
                if (type.equals(Enterprise.EnterpriseType.PHD.getValue())) {
                    PHDEnterprise phd = new PHDEnterprise();
                    Enterprise enterprise = phd;
                    phd.setLocation(location);
                    phd.setAddress(address);
                    phd.setContactName(contactName);
                    phd.setContactNumber(contactNumber);
                    phd.setEmailId(emailId);
                    phd.setEnterpriseName(enterpriseName);
                    network.getEnterpriseDirectory().getEnterpriseList().add(phd);
                    enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Admin);
                }
                if (type.equals(Enterprise.EnterpriseType.Manufacturer.getValue())) {
                    boolean manufFlag = false;
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.Manufacturer.getValue())) {
                            ManufacturerEnterprise me = (ManufacturerEnterprise) enterprise;
                            if (!me.isBlacklisted()) {
                                manufFlag = true;
                                break;
                            }
                        }
                    }
                    if (!manufFlag) {
                        ManufacturerEnterprise manufacturer = new ManufacturerEnterprise();
                        Enterprise enterprise = manufacturer;
                        manufacturer.setLocation(location);
                        manufacturer.setAddress(address);
                        manufacturer.setContactName(contactName);
                        manufacturer.setContactNumber(contactNumber);
                        manufacturer.setEmailId(emailId);
                        manufacturer.setEnterpriseName(enterpriseName);
                        network.getEnterpriseDirectory().getEnterpriseList().add(manufacturer);
                        enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Admin);
                        enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Finance);
                        JOptionPane.showMessageDialog(null, "Details Submitted");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Manufacturer already exists");
                    }
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter appropriate details");
        }
        cityJTextField.setText(null);
        contactNameJTextField.setText(null);
        contactNumberJTextField.setText(null);
        emailIdJTextField.setText(null);
        stateComboBox.setSelectedIndex(0);
        enterpriseComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextFieldActionPerformed

    private void contactNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNameJTextFieldActionPerformed

    private void emailIdJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdJTextFieldActionPerformed

    private void contactNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberJTextFieldActionPerformed

    private void enterpriseNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameJTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField contactNameJTextField;
    private javax.swing.JTextField contactNumberJTextField;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JTextField enterpriseNameJTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkTable;
    private javax.swing.JButton removeEnterpriseButton;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
