/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManufacturerFinance;

import Business.CDCSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import UserInterface.ProviderAdmin.UpdatePersonalInfoJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Danisha
 */
public class ManufacturerFinanceWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturerFinanceWorkArea
     */
    private JPanel userProcessContainer;
    private CDCSystem system;
    private DB4OUtil db4oUtil;
    private UserAccount account;
    private Enterprise enterprise;
    public ManufacturerFinanceWorkArea(JPanel userProcessContainer, CDCSystem system, DB4OUtil db4oUtil, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system= system;
        this.db4oUtil= db4oUtil;
        this.account= account;
        this.enterprise= enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageTreasuryButton = new javax.swing.JButton();
        updatePersonalInfoButton2 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        manageReceivingPaymentsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manufacturer Finance Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 309, 40));

        manageTreasuryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageTreasuryButton.setText("Manage Treasury");
        manageTreasuryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTreasuryButtonActionPerformed(evt);
            }
        });
        add(manageTreasuryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 245, -1));

        updatePersonalInfoButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePersonalInfoButton2.setText("Update Personal Info");
        updatePersonalInfoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePersonalInfoButton2ActionPerformed(evt);
            }
        });
        add(updatePersonalInfoButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 245, -1));

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 245, -1));

        manageReceivingPaymentsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageReceivingPaymentsButton.setText("Manage Receiving Payments");
        manageReceivingPaymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReceivingPaymentsButtonActionPerformed(evt);
            }
        });
        add(manageReceivingPaymentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 245, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageTreasuryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTreasuryButtonActionPerformed
        // TODO add your handling code here:
        ManageTreasuryManufJPanel manageTreasuryManuf = new ManageTreasuryManufJPanel(userProcessContainer, system, enterprise, account);
        userProcessContainer.add("ManageTreasuryManufJPanel", manageTreasuryManuf);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageTreasuryButtonActionPerformed

    private void updatePersonalInfoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePersonalInfoButton2ActionPerformed
        // TODO add your handling code here:
        UpdatePersonalInfoJPanel updatePersonalInfoJPanel = new UpdatePersonalInfoJPanel(userProcessContainer, system, account);
        userProcessContainer.add("updatePersonalInfoJPanel", updatePersonalInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updatePersonalInfoButton2ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        db4oUtil.storeSystem(system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void manageReceivingPaymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReceivingPaymentsButtonActionPerformed
        // TODO add your handling code here:

        ReceivingPaymentsManufJPanel receivingPaymentsManuf = new ReceivingPaymentsManufJPanel(userProcessContainer, system, enterprise, account);
        userProcessContainer.add("ReceivingPaymentsManufJPanel", receivingPaymentsManuf);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReceivingPaymentsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageReceivingPaymentsButton;
    private javax.swing.JButton manageTreasuryButton;
    private javax.swing.JButton updatePersonalInfoButton2;
    // End of variables declaration//GEN-END:variables
}
